'use strict';

module.exports = function(locals) {
  var style='<style>  .clearfix{    clear:both;  }  #tabs{    margin-bottom: 15px;    margin-top:15px;  }  #tabs a {    padding: 5px;  }  #tabs a.active{    background: #657b83;    color: #fff;  }  #collections .book{            padding-bottom: 10px;    position: relative;    clear: both;    min-height: 170px;    padding: 10px 0;    border-bottom: 1px #ddd solid;  }  .book .picture{    position: absolute;    left: 0;    top: 10px;  }  .book .info{    padding-left: 120px;  }  .book .meta{    font-size: 12px;    padding-right: 10px;  }  .book .comments{    font-size: 12px;  }  .hide{    display: none;  }  #collections .active{    display: block;  }  @media screen and (max-width:600px) {    #collections .book{      width: 100%;    }  }  #refresh{    color: red;  }</style>'

  var quote='<div><blockquote><p>大学即将结束之际，开始用<a href="https://www.douban.com/people/mythsman/">豆瓣</a>记录我的阅读。</p></blockquote></div>'

  var control='<div id="loading"><p>    正在加载...</p></div><div id="douban"><div id="tabs"><a id="reading-tab" href="javascript:show(\'reading\')" target="_blank" rel="external">在读<span id="reading-total"></span></a><a id="wish-tab" href="javascript:show(\'wish\')" target="_blank" rel="external">想读<span id="wish-total"></span></a><a id="read-tab" href="javascript:show(\'read\')" target="_blank" rel="external">已读<span id="read-total"></span></a></div><div id="collections"><div id="reading" class="hide"></div><div class="clearfix"></div><div id="wish" class="hide"></div><div class="clearfix"></div><div id="read" class="hide"></div><div class="clearfix"></div></div></div>'

  var js='function show(id){document.getElementById("reading").classList.remove("active");document.getElementById("read").classList.remove("active");document.getElementById("wish").classList.remove("active");document.getElementById("reading").classList.add("hide");document.getElementById("read").classList.add("hide");document.getElementById("wish").classList.add("hide");var ele=document.getElementById(id);ele.classList.remove("hide");ele.classList.add("active");document.getElementById("reading-tab").classList.remove("active");document.getElementById("read-tab").classList.remove("active");document.getElementById("wish-tab").classList.remove("active");document.getElementById(id+"-tab").classList.add("active")}(function(){var read=[];var wish=[];var reading=[];function loadDoubanCollections(){var xhr=new XMLHttpRequest();xhr.open("GET","/read/collections.json",true);xhr.onload=function(){if(this.status>=200&&this.status<300){var res=JSON.parse(this.response);searchData=res;onLoadDouban(searchData)}else{console.error(this.statusText)}};xhr.onerror=function(){console.error(this.statusText)};xhr.send()}function onLoadDouban(data){if(data["count"]>0){for(var i=0;i<data["collections"].length;++i){resolveBook(data["collections"][i])}}render()}function resolveBook(book){if(book["status"]=="read"){read.push(book)}if(book["status"]=="wish"){wish.push(book)}if(book["status"]=="reading"){reading.push(book)}}function render(){renderList(read,"read");renderList(wish,"wish");renderList(reading,"reading");document.getElementById("reading-total").innerHTML="("+reading.length+")";document.getElementById("read-total").innerHTML="("+read.length+")";document.getElementById("wish-total").innerHTML="("+wish.length+")";show("reading");document.getElementById("loading").classList.add("hide")}function renderList(list,id){for(var i=0;i<list.length;++i){var h=renderBook(list[i]);if(i>0&&i%4==3){h+=\'<div class="clearfix"></div>\'}document.getElementById(id).innerHTML=document.getElementById(id).innerHTML+h}}function renderBook(book){var html=\'<div class="book book-\'+book["status"]+\'">\'+\'<div class="picture"><img src="\'+book.book.image+\'"/></div><div class="info">\'+\'<div class="title"><a target="_blank" href="\'+book.book.alt+\'">\'+book.book.title+"</a></div>"+\'<div class="meta">\'+book.book.author[0]+" / "+book.book.pubdate+" / "+book.book.rating.average+"分</div>"+\'<div class="meta">\'+book.updated.substring(0,10)+resolveRating(book.rating)+resolveTags(book.tags)+"</div>"+\'<div class="comments">\'+(book.comment?book.comment:"")+"</div>"+"</div>"+"</div>";return html}function resolveRating(rating){if(rating&&rating.value){return" / "+rating.value+"星"}return""}function resolveTags(tags){if(tags&&tags.length>0){var html=" / ";for(var i=0;i<tags.length;++i){html+=tags[i]+" "}return html}return""}loadDoubanCollections()})();'

  return style+quote+control+js
};
